name: "Create Universal Artifact"
description: | 
  "Actions para crear un directorio donde alojar los archivos requeridos para la construcción de un artefacto."
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'package'
  color: 'white'
inputs:
  work_dir:
    description: 'Directorio del repositorio'
    required: true
  artifact_name:
    description: 'Nombre del artefacto'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        mkdir -p ${{ inputs.work_dir }}/${{ inputs.artifact_name }}
        cd ${{ inputs.work_dir }} && ls -l
      shell: bash
