name: "Create Universal Artifact"
description: | 
  "Actions para crear un directorio donde alojar los archivos requeridos para la construcción de un artefacto."
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'package'
  color: 'white'
inputs:
  work_dir:
    description: 'Directorio del repositorio'
    required: true
  artifact_name:
    description: 'Nombre del artefacto'
    required: true
  run_numbe:
    description: 'número de ejecución de workflow'
    default: ""
runs:
  using: 'composite'
  steps:
    - run: |
        if [ ${{ inputs.run_numbe }} -eq "false" ]
        then
          mkdir -p ${{ inputs.work_dir }}/${{ inputs.artifact_name }}
        else
          mkdir -p ${{ inputs.work_dir }}/${{ inputs.artifact_name }}${{ inputs.run_numbe }}
        fi
        cd ${{ inputs.work_dir }} && ls -l
      shell: bash
